"""
Django settings for wikiclub project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information, see:
https://docs.djangoproject.com/en/5.2/topics/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zk-8oa#90q$4vrp3pr*rp#vgoo(6j+4$#5&n+6)#t#yv2vj6o2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["wikiclub.onrender.com", "wikiclub.in"]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'corsheaders',

    # Local
    'users',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "https://wikiclub.in",
]

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'wikiclub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wikiclub.wsgi.application'

# ✅ Production PostgreSQL from Render (External URL)
DATABASES = {
    'default': dj_database_url.parse(
        os.environ.get("DATABASE_URL") or
        "postgresql://wikiclub_db_user:aQGvEsS09z9OeDxa3MdrxyE0lE8Wy2H3@dpg-d0g65u49c44c73faf9c0-a.singapore-postgres.render.com/wikiclub_db",
        conn_max_age=600,
        ssl_require=True
    )
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Localization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'

# Default primary key type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'users.CustomUser'

# OAuth2 Wikimedia config
WIKI_CLIENT_ID = os.environ.get("WIKI_CLIENT_ID")
WIKI_CLIENT_SECRET = os.environ.get("WIKI_CLIENT_SECRET")
WIKI_REDIRECT_URI = os.environ.get("WIKI_REDIRECT_URI")
